// Service type definition
export interface Service {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string;
  categoryGroup: string;
  
  // Domestic pricing (all in INR)
  statutoryFee: number;
  professionalFee: number;
  gst: number;
  totalPayable: number;
  
  // NRI premium pricing (all in INR)
  nriGovtFee: number;
  nriProfFee: number;
  nriGst: number;
  nriTotalPayable: number;
  
  // Multi-currency prices (NRI)
  priceUSD: number;
  priceGBP: number;
  priceAED: number;
  
  processingTime: string;
  requiredDocuments: string[];
  popular?: boolean;
  
  // Feasibility flags
  isFullyOnline?: boolean;
  requiresPhysicalPresence?: boolean;
  requiresSiteInspection?: boolean;
  isStatutoryFeeVariable?: boolean;
  statutoryFeeNote?: string;
  operationalComplexity?: 'low' | 'medium' | 'high';
  
  // Sub-services
  hasSubServices: boolean;
  subServices?: Array<{
    value: string;
    label: string;
    description: string;
    additionalDocs: string[];
  }>;
}

export const services: Service[] = [
  // ========================================
  // IDENTITY & CARDS (10 Active Services)
  // ========================================
  
  {
    id: 'aadhaar-update',
    slug: 'aadhaar-update',
    name: 'Aadhaar Update Services',
    description: 'Update demographic information in Aadhaar - 100% online',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 399,
    gst: 72,
    totalPayable: 471,
    nriGovtFee: 50,
    nriProfFee: 2500,
    nriGst: 450,
    nriTotalPayable: 3000,
    priceUSD: 36,
    priceGBP: 29,
    priceAED: 135,
    processingTime: '5-7 working days',
    requiredDocuments: ['Aadhaar Card', 'Proof of Update Required'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'address-change', label: 'Address Change', description: 'Update address in Aadhaar - 100% online', additionalDocs: ['Proof of new address (utility bill/ration card)'] },
      { value: 'mobile-update', label: 'Mobile Number Update', description: 'Update mobile number - 100% online', additionalDocs: ['Registered mobile number for OTP verification'] },
      { value: 'name-correction', label: 'Name Correction', description: 'Correct name in Aadhaar - 100% online', additionalDocs: ['Proof of Name (passport, PAN card)'] },
      { value: 'dob-correction', label: 'Date of Birth Correction', description: 'Correct date of birth - 100% online', additionalDocs: ['Birth Certificate or Passport'] },
      { value: 'gender-correction', label: 'Gender Correction', description: 'Correct gender - 100% online', additionalDocs: ['Valid ID with correct gender'] },
      { value: 'email-update', label: 'Email Update', description: 'Update email address - 100% online', additionalDocs: ['Registered mobile number for OTP'] }
    ]
  },

  {
    id: 'pan-card',
    slug: 'pan-card',
    name: 'PAN Card Services',
    description: 'PAN card application, correction, and reprint - 100% online',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 110,
    professionalFee: 399,
    gst: 72,
    totalPayable: 581,
    nriGovtFee: 107,
    nriProfFee: 4000,
    nriGst: 720,
    nriTotalPayable: 4827,
    priceUSD: 58,
    priceGBP: 46,
    priceAED: 215,
    processingTime: '7-15 days',
    requiredDocuments: ['Aadhaar Card', 'Photograph', 'Signature', 'Date of Birth Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'new-pan', label: 'New PAN Card', description: 'Apply for new PAN card - instant e-PAN', additionalDocs: ['Date of Birth Proof', 'Address Proof'] },
      { value: 'pan-correction', label: 'PAN Correction', description: 'Correct name, DOB, or father\'s name', additionalDocs: ['Existing PAN', 'Proof of Correction'] },
      { value: 'pan-reprint', label: 'PAN Reprint', description: 'Reprint lost or damaged PAN card', additionalDocs: ['PAN Number', 'Aadhaar'] },
      { value: 'pan-address', label: 'Update Address', description: 'Change address in PAN records', additionalDocs: ['Existing PAN', 'New Address Proof'] },
      { value: 'pan-contact', label: 'Update Phone/Email', description: 'Update contact details', additionalDocs: ['Existing PAN', 'Aadhaar'] },
      { value: 'pan-aadhaar-link', label: 'Link PAN with Aadhaar', description: 'Link PAN and Aadhaar', additionalDocs: ['PAN Card', 'Aadhaar Card'] }
    ]
  },

  {
    id: 'voter-id-card',
    slug: 'voter-id-card',
    name: 'Voter ID Card Services',
    description: 'Voter ID enrollment, corrections, and updates - 100% online',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 500,
    gst: 90,
    totalPayable: 590,
    nriGovtFee: 0,
    nriProfFee: 3000,
    nriGst: 540,
    nriTotalPayable: 3540,
    priceUSD: 42,
    priceGBP: 34,
    priceAED: 155,
    processingTime: '30-60 days',
    requiredDocuments: ['Address Proof', 'Age Proof', 'Passport Size Photos', 'Aadhaar Card'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: true,
    subServices: [
      { value: 'new', label: 'New Voter ID Enrollment', description: 'First-time voter registration - 100% online', additionalDocs: [] },
      { value: 'correction', label: 'Correction in Existing Card', description: 'Fix name, photo, or details - 100% online', additionalDocs: ['Existing Voter ID'] },
      { value: 'address_change', label: 'Address Change (Same Constituency)', description: 'Update address - 100% online', additionalDocs: ['New Address Proof', 'Old Voter ID'] },
      { value: 'address_transfer', label: 'Address Change (Different Constituency)', description: 'Transfer constituency - 100% online', additionalDocs: ['New Address Proof', 'Old Voter ID'] },
      { value: 'duplicate', label: 'Duplicate Voter ID', description: 'Reissue lost or damaged card - 100% online', additionalDocs: ['FIR Copy (if lost)', 'Application'] },
      { value: 'deletion', label: 'Delete Duplicate Entry', description: 'Remove incorrect entry - 100% online', additionalDocs: ['Proof of Correction', 'Identity Proof'] }
    ]
  },

  {
    id: 'driving-license',
    slug: 'driving-license',
    name: 'Driving License Services',
    description: 'Learner license and DL renewal - online services',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 150,
    professionalFee: 699,
    gst: 126,
    totalPayable: 975,
    nriGovtFee: 200,
    nriProfFee: 5000,
    nriGst: 900,
    nriTotalPayable: 6100,
    priceUSD: 73,
    priceGBP: 58,
    priceAED: 270,
    processingTime: '7-15 days',
    requiredDocuments: ['Aadhaar Card', 'Address Proof', 'Age Proof', 'Passport Size Photos'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'learner', label: "Learner's License (LL)", description: 'Online test via Aadhaar proctoring - 100% online', additionalDocs: ['Age Proof', 'Address Proof'] },
      { value: 'renewal', label: 'License Renewal', description: 'Renew expired license - mostly online', additionalDocs: ['Old License', 'Medical Certificate (if 40+)'] }
    ]
  },

  {
    id: 'birth-certificate',
    slug: 'birth-certificate',
    name: 'Birth Certificate Services',
    description: 'Birth certificate - new, correction, and duplicate - 100% online',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 50,
    professionalFee: 399,
    gst: 72,
    totalPayable: 521,
    nriGovtFee: 300,
    nriProfFee: 2400,
    nriGst: 432,
    nriTotalPayable: 3132,
    priceUSD: 38,
    priceGBP: 30,
    priceAED: 140,
    processingTime: '15-30 days',
    requiredDocuments: ['Hospital Birth Certificate', 'Parents ID', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'new', label: 'New Birth Certificate', description: 'Institutional births - instant online download', additionalDocs: ['Hospital Birth Certificate'] },
      { value: 'correction', label: 'Birth Certificate Correction', description: 'Correct name, DOB, or parent names', additionalDocs: ['Existing Certificate', 'Proof of Correction'] },
      { value: 'duplicate', label: 'Duplicate Birth Certificate', description: 'Download lost certificate', additionalDocs: ['Birth Registration Number'] }
    ]
  },

  {
    id: 'death-certificate',
    slug: 'death-certificate',
    name: 'Death Certificate Services',
    description: 'Death certificate - new, correction, and duplicate - 100% online',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 50,
    professionalFee: 399,
    gst: 72,
    totalPayable: 521,
    nriGovtFee: 300,
    nriProfFee: 2400,
    nriGst: 432,
    nriTotalPayable: 3132,
    priceUSD: 38,
    priceGBP: 30,
    priceAED: 140,
    processingTime: '15-30 days',
    requiredDocuments: ['Hospital Death Certificate', 'Deceased ID', 'Applicant ID'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'new', label: 'New Death Certificate', description: 'Institutional deaths - instant online download', additionalDocs: ['Hospital Death Certificate'] },
      { value: 'correction', label: 'Death Certificate Correction', description: 'Correct name, DOB, or details', additionalDocs: ['Existing Certificate', 'Proof of Correction'] },
      { value: 'duplicate', label: 'Duplicate Death Certificate', description: 'Download lost certificate', additionalDocs: ['Death Registration Number'] }
    ]
  },

  {
    id: 'income-certificate',
    slug: 'income-certificate',
    name: 'Income Certificate Services',
    description: 'Income certificates for various income sources - 100% online',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61,
    totalPayable: 421,
    nriGovtFee: 120,
    nriProfFee: 2040,
    nriGst: 367,
    nriTotalPayable: 2527,
    priceUSD: 30,
    priceGBP: 25,
    priceAED: 112,
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Income Proof', 'Address Proof', 'Bank Statement'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'salary', label: 'Salary-Based Income Certificate', description: 'For salaried employees', additionalDocs: ['Salary Slips (6 months)', 'Employer Letter'] },
      { value: 'business', label: 'Business Income Certificate', description: 'For self-employed/business owners', additionalDocs: ['GST Returns', 'Bank Statements', 'IT Returns'] },
      { value: 'agricultural', label: 'Agricultural Income Certificate', description: 'For farmers', additionalDocs: ['Land Records', 'Patta Copy', 'Crop Details'] },
      { value: 'no-income', label: 'No Income Certificate', description: 'For unemployed/students', additionalDocs: ['Self-Declaration', 'Educational Certificates'] }
    ]
  },

  {
    id: 'caste-certificate',
    slug: 'caste-certificate',
    name: 'Caste Certificate',
    description: 'Official caste certificate for SC/ST/OBC categories',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 20,
    professionalFee: 499,
    gst: 90,
    totalPayable: 609,
    nriGovtFee: 120,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3653,
    priceUSD: 44,
    priceGBP: 35,
    priceAED: 162,
    processingTime: '30-45 days',
    requiredDocuments: ['Aadhaar', 'Community Proof', 'School Certificate', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'residence-certificate',
    slug: 'residence-certificate',
    name: 'Residence/Domicile Certificate',
    description: 'Proof of residence certificate',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61,
    totalPayable: 421,
    nriGovtFee: 120,
    nriProfFee: 2040,
    nriGst: 367,
    nriTotalPayable: 2527,
    priceUSD: 30,
    priceGBP: 25,
    priceAED: 112,
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Address Proof (10+ years)', 'School Certificate', 'Property Documents'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'senior-citizen-card',
    slug: 'senior-citizen-card',
    name: 'Senior Citizen Card',
    description: 'Senior citizen identification card',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 54,
    totalPayable: 353,
    nriGovtFee: 0,
    nriProfFee: 1794,
    nriGst: 323,
    nriTotalPayable: 2117,
    priceUSD: 26,
    priceGBP: 21,
    priceAED: 94,
    processingTime: '15-30 days',
    requiredDocuments: ['Age Proof (60+ years)', 'Aadhaar', 'Photograph', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  // ========================================
  // REVENUE CERTIFICATES (12 Services)
  // ========================================
  {
    id: 'community-certificate',
    slug: 'community-certificate',
    name: 'Community Certificate',
    description: 'Official community/caste certificate from Tahsildar',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61,
    totalPayable: 421,
    nriGovtFee: 120,
    nriProfFee: 2040,
    nriGst: 367,
    nriTotalPayable: 2527,
    priceUSD: 30,
    priceGBP: 25,
    priceAED: 112,
    processingTime: '30-45 days',
    requiredDocuments: ['Aadhaar', 'Community Proof', 'School Certificate', 'Address Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: true,
    subServices: [
      { value: 'bc', label: 'Backward Class (BC)', description: 'Certificate for BC community members', additionalDocs: ['School Certificate', 'Parent Community Certificate'] },
      { value: 'mbc', label: 'Most Backward Class (MBC)', description: 'Certificate for MBC community members', additionalDocs: ['School Certificate', 'Parent Community Certificate'] },
      { value: 'sc', label: 'Scheduled Caste (SC)', description: 'Certificate for SC community members', additionalDocs: ['School Certificate', 'Parent Community Certificate'] },
      { value: 'st', label: 'Scheduled Tribe (ST)', description: 'Certificate for ST community members', additionalDocs: ['School Certificate', 'Parent Community Certificate'] }
    ]
  },

  {
    id: 'nativity-certificate',
    slug: 'nativity-certificate',
    name: 'Nativity Certificate',
    description: 'Birth place certificate from Tahsildar office',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61,
    totalPayable: 421,
    nriGovtFee: 120,
    nriProfFee: 2040,
    nriGst: 367,
    nriTotalPayable: 2527,
    priceUSD: 30,
    priceGBP: 25,
    priceAED: 112,
    processingTime: '15-30 days',
    requiredDocuments: ['Birth Certificate', 'School Certificate', 'Address Proof', 'Aadhaar'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'first-graduate-certificate',
    slug: 'first-graduate-certificate',
    name: 'First Graduate Certificate',
    description: 'Certificate for first in family to pursue higher education',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 60,
    professionalFee: 590,
    gst: 106,
    totalPayable: 756,
    nriGovtFee: 360,
    nriProfFee: 3540,
    nriGst: 637,
    nriTotalPayable: 4537,
    priceUSD: 55,
    priceGBP: 44,
    priceAED: 201,
    processingTime: '30-45 days',
    requiredDocuments: ['Educational Certificates of Parents', 'Family Details', 'Ration Card', 'Self-Declaration'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'legal-heir-certificate',
    slug: 'legal-heir-certificate',
    name: 'Legal Heir Certificate',
    description: 'Official legal heir certificate from revenue department',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 50,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2409,
    nriGovtFee: 300,
    nriProfFee: 11994,
    nriGst: 2159,
    nriTotalPayable: 14453,
    priceUSD: 174,
    priceGBP: 140,
    priceAED: 641,
    processingTime: '30-60 days',
    requiredDocuments: ['Death Certificate', 'Family Details', 'Ration Card', 'Property Details'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'high',
    hasSubServices: false
  },

  {
    id: 'widow-certificate',
    slug: 'widow-certificate',
    name: 'Widow Certificate',
    description: 'Widow certificate for pension schemes',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 60,
    professionalFee: 390,
    gst: 70,
    totalPayable: 520,
    nriGovtFee: 360,
    nriProfFee: 2340,
    nriGst: 421,
    nriTotalPayable: 3121,
    priceUSD: 38,
    priceGBP: 30,
    priceAED: 139,
    processingTime: '30-45 days',
    requiredDocuments: ['Death Certificate (Husband)', 'Marriage Certificate', 'Identity Proof', 'Income Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'deserted-woman-certificate',
    slug: 'deserted-woman-certificate',
    name: 'Deserted Woman Certificate',
    description: 'Certificate for deserted women',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 60,
    professionalFee: 540,
    gst: 97,
    totalPayable: 697,
    nriGovtFee: 360,
    nriProfFee: 3240,
    nriGst: 583,
    nriTotalPayable: 4183,
    priceUSD: 50,
    priceGBP: 41,
    priceAED: 186,
    processingTime: '45-60 days',
    requiredDocuments: ['Marriage Certificate', 'Proof of Desertion', 'Identity Proof', 'Income Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'inter-caste-marriage-certificate',
    slug: 'inter-caste-marriage-certificate',
    name: 'Inter-Caste Marriage Certificate',
    description: 'Certificate for inter-caste marriage benefits - 100% online',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 0,
    professionalFee: 999,
    gst: 180,
    totalPayable: 1179,
    nriGovtFee: 0,
    nriProfFee: 5994,
    nriGst: 1079,
    nriTotalPayable: 7073,
    priceUSD: 85,
    priceGBP: 69,
    priceAED: 313,
    processingTime: '30-60 days',
    requiredDocuments: ['Marriage Certificate', 'Caste Certificates', 'Joint Affidavit', 'Photos'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'family-card',
    slug: 'family-card',
    name: 'Family Card',
    description: 'Family identity card from local body',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 0,
    professionalFee: 399,
    gst: 72,
    totalPayable: 471,
    nriGovtFee: 0,
    nriProfFee: 2394,
    nriGst: 431,
    nriTotalPayable: 2825,
    priceUSD: 34,
    priceGBP: 27,
    priceAED: 126,
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar (All members)', 'Address Proof', 'Family Details'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'no-objection-certificate',
    slug: 'no-objection-certificate',
    name: 'No Objection Certificate',
    description: 'General purpose NOC from authorities',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 100,
    professionalFee: 799,
    gst: 144,
    totalPayable: 1043,
    nriGovtFee: 600,
    nriProfFee: 4794,
    nriGst: 863,
    nriTotalPayable: 6257,
    priceUSD: 75,
    priceGBP: 61,
    priceAED: 279,
    processingTime: '15-30 days',
    requiredDocuments: ['Purpose Details', 'Supporting Documents', 'ID Proof'],
    popular: false,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'solvency-certificate',
    slug: 'solvency-certificate',
    name: 'Solvency Certificate',
    description: 'Financial solvency certificate from Tahsildar for loans, tenders, and contracts',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 20,
    professionalFee: 340,
    gst: 61,
    totalPayable: 421,
    nriGovtFee: 120,
    nriProfFee: 2040,
    nriGst: 367,
    nriTotalPayable: 2527,
    priceUSD: 30,
    priceGBP: 25,
    priceAED: 112,
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Property Documents', 'Bank Statements', 'IT Returns', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'unemployment-certificate',
    slug: 'unemployment-certificate',
    name: 'Unemployment Certificate',
    description: 'Official unemployment certificate from employment office for various schemes',
    category: 'certificates',
    categoryGroup: 'Revenue Certificates',
    statutoryFee: 20,
    professionalFee: 299,
    gst: 54,
    totalPayable: 373,
    nriGovtFee: 120,
    nriProfFee: 1794,
    nriGst: 323,
    nriTotalPayable: 2237,
    priceUSD: 27,
    priceGBP: 22,
    priceAED: 99,
    processingTime: '15-30 days',
    requiredDocuments: ['Aadhaar', 'Educational Certificates', 'Employment Office Registration', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  // ========================================
  // PROPERTY & ASSETS (8 Services - Online Only)
  // ========================================
  {
    id: 'patta-services',
    slug: 'patta-services',
    name: 'Patta Services',
    description: 'Patta transfer and land record services - online',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 60,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 1829,
    nriGovtFee: 360,
    nriProfFee: 8994,
    nriGst: 1619,
    nriTotalPayable: 10973,
    priceUSD: 132,
    priceGBP: 107,
    priceAED: 483,
    processingTime: '60-90 days',
    requiredDocuments: ['Registered Sale Deed', 'Old Patta', 'Survey Documents', 'Encumbrance Certificate'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'high',
    hasSubServices: true,
    subServices: [
      { value: 'transfer-full', label: 'Patta Transfer - Full Field', description: 'Complete property transfer - 100% online', additionalDocs: ['Sale Deed', 'Previous Patta', 'Tax Receipts'] },
      { value: 'transfer-joint', label: 'Patta Transfer - Joint/Partiable', description: 'Joint ownership transfer - 100% online', additionalDocs: ['Sale Deed', 'Previous Patta', 'Tax Receipts', 'Partition Deed'] },
      { value: 'name-correction', label: 'Patta Name Correction', description: 'Fix name errors in patta - 100% online', additionalDocs: ['ID Proof with Correct Name', 'Patta Copy'] }
    ]
  },

  {
    id: 'encumbrance-certificate',
    slug: 'encumbrance-certificate',
    name: 'Encumbrance Certificate',
    description: 'Property legal status verification certificate',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 50,
    professionalFee: 499,
    gst: 90,
    totalPayable: 639,
    nriGovtFee: 300,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3833,
    priceUSD: 46,
    priceGBP: 37,
    priceAED: 169,
    processingTime: '7-15 days',
    requiredDocuments: ['Property Details', 'Survey Number', 'Village Details', 'Time Period'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'property-tax-payment',
    slug: 'property-tax-payment',
    name: 'Property Tax Payment',
    description: 'Municipal property tax payment',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 0,
    professionalFee: 199,
    gst: 36,
    totalPayable: 235,
    nriGovtFee: 0,
    nriProfFee: 1194,
    nriGst: 215,
    nriTotalPayable: 1409,
    priceUSD: 17,
    priceGBP: 14,
    priceAED: 62,
    processingTime: '1-3 days',
    requiredDocuments: ['Property Details', 'Previous Tax Receipt', 'Owner ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'property-registration',
    slug: 'property-registration',
    name: 'Property Document Registration',
    description: 'Sale deed and property document registration assistance',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 0,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 3539,
    nriGovtFee: 0,
    nriProfFee: 17994,
    nriGst: 3239,
    nriTotalPayable: 21233,
    priceUSD: 256,
    priceGBP: 206,
    priceAED: 937,
    processingTime: '7-15 days',
    requiredDocuments: ['Sale Agreement', 'Encumbrance Certificate', 'Property Tax Receipt', 'IDs'],
    popular: true,
    isStatutoryFeeVariable: true,
    statutoryFeeNote: 'Registration fee varies (7% of property value)',
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'khata-extract',
    slug: 'khata-extract',
    name: 'Khata Extract',
    description: 'Property khata details from municipal records',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 20,
    professionalFee: 299,
    gst: 54,
    totalPayable: 373,
    nriGovtFee: 120,
    nriProfFee: 1794,
    nriGst: 323,
    nriTotalPayable: 2237,
    priceUSD: 27,
    priceGBP: 22,
    priceAED: 99,
    processingTime: '3-7 days',
    requiredDocuments: ['Property Details', 'Owner ID', 'Tax Receipt'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'mutation-certificate',
    slug: 'mutation-certificate',
    name: 'Mutation Certificate',
    description: 'Update land records after ownership change',
    category: 'property',
    categoryGroup: 'Property & Assets',
    statutoryFee: 100,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 1869,
    nriGovtFee: 600,
    nriProfFee: 8994,
    nriGst: 1619,
    nriTotalPayable: 11213,
    priceUSD: 135,
    priceGBP: 109,
    priceAED: 495,
    processingTime: '30-60 days',
    requiredDocuments: ['Registered Sale Deed', 'Previous Records', 'Tax Receipts', 'Survey Map'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  // ========================================
  // WELFARE SCHEMES (17 Services)
  // ========================================
  {
    id: 'old-age-pension',
    slug: 'old-age-pension',
    name: 'Old Age Pension Scheme',
    description: 'Monthly pension for senior citizens',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 108,
    totalPayable: 707,
    nriGovtFee: 0,
    nriProfFee: 3594,
    nriGst: 647,
    nriTotalPayable: 4241,
    priceUSD: 51,
    priceGBP: 41,
    priceAED: 187,
    processingTime: '30-60 days',
    requiredDocuments: ['Age Proof (60+ years)', 'Income Certificate', 'Bank Details', 'Aadhaar'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'widow-pension',
    slug: 'widow-pension',
    name: 'Widow Pension Scheme',
    description: 'Financial assistance for widows',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 108,
    totalPayable: 707,
    nriGovtFee: 0,
    nriProfFee: 3594,
    nriGst: 647,
    nriTotalPayable: 4241,
    priceUSD: 51,
    priceGBP: 41,
    priceAED: 187,
    processingTime: '30-60 days',
    requiredDocuments: ['Widow Certificate', 'Death Certificate', 'Income Certificate', 'Bank Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'disability-pension',
    slug: 'disability-pension',
    name: 'Disability Pension Scheme',
    description: 'Pension for differently abled persons',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 144,
    totalPayable: 943,
    nriGovtFee: 0,
    nriProfFee: 4794,
    nriGst: 863,
    nriTotalPayable: 5657,
    priceUSD: 68,
    priceGBP: 55,
    priceAED: 249,
    processingTime: '30-60 days',
    requiredDocuments: ['Disability Certificate', 'Income Certificate', 'Bank Details', 'Medical Reports'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'deserted-woman-pension',
    slug: 'deserted-woman-pension',
    name: 'Deserted Woman Pension',
    description: 'Financial support for deserted women',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 144,
    totalPayable: 943,
    nriGovtFee: 0,
    nriProfFee: 4794,
    nriGst: 863,
    nriTotalPayable: 5657,
    priceUSD: 68,
    priceGBP: 55,
    priceAED: 249,
    processingTime: '30-60 days',
    requiredDocuments: ['Deserted Woman Certificate', 'Income Certificate', 'Bank Details', 'Aadhaar'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'scholarship-sc-st',
    slug: 'scholarship-sc-st',
    name: 'SC/ST Scholarship',
    description: 'Educational scholarship for SC/ST students',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 499,
    gst: 90,
    totalPayable: 589,
    nriGovtFee: 0,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3533,
    priceUSD: 43,
    priceGBP: 34,
    priceAED: 156,
    processingTime: '30-60 days',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Mark Sheets', 'Bank Details', 'College ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'scholarship-bc-mbc',
    slug: 'scholarship-bc-mbc',
    name: 'BC/MBC Scholarship',
    description: 'Educational scholarship for BC/MBC students',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 499,
    gst: 90,
    totalPayable: 589,
    nriGovtFee: 0,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3533,
    priceUSD: 43,
    priceGBP: 34,
    priceAED: 156,
    processingTime: '30-60 days',
    requiredDocuments: ['Community Certificate', 'Income Certificate', 'Mark Sheets', 'Bank Details', 'College ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'scholarship-minority',
    slug: 'scholarship-minority',
    name: 'Minority Community Scholarship',
    description: 'Educational scholarship for minority students',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 499,
    gst: 90,
    totalPayable: 589,
    nriGovtFee: 0,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3533,
    priceUSD: 43,
    priceGBP: 34,
    priceAED: 156,
    processingTime: '30-60 days',
    requiredDocuments: ['Community Certificate', 'Income Certificate', 'Mark Sheets', 'Bank Details', 'College ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'maternity-benefit',
    slug: 'maternity-benefit',
    name: 'Maternity Benefit Scheme',
    description: 'Financial assistance for pregnant women',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 108,
    totalPayable: 707,
    nriGovtFee: 0,
    nriProfFee: 3594,
    nriGst: 647,
    nriTotalPayable: 4241,
    priceUSD: 51,
    priceGBP: 41,
    priceAED: 187,
    processingTime: '30-60 days',
    requiredDocuments: ['Pregnancy Certificate', 'Aadhaar', 'Bank Details', 'Hospital Records'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'marriage-assistance',
    slug: 'marriage-assistance',
    name: 'Marriage Assistance Scheme',
    description: 'Financial aid for marriages',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 144,
    totalPayable: 943,
    nriGovtFee: 0,
    nriProfFee: 4794,
    nriGst: 863,
    nriTotalPayable: 5657,
    priceUSD: 68,
    priceGBP: 55,
    priceAED: 249,
    processingTime: '30-60 days',
    requiredDocuments: ['Marriage Certificate', 'Income Certificate', 'Bank Details', 'Community Certificate'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'funeral-assistance',
    slug: 'funeral-assistance',
    name: 'Funeral Assistance Scheme',
    description: 'Financial support for last rites',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 399,
    gst: 72,
    totalPayable: 471,
    nriGovtFee: 0,
    nriProfFee: 2394,
    nriGst: 431,
    nriTotalPayable: 2825,
    priceUSD: 34,
    priceGBP: 27,
    priceAED: 126,
    processingTime: '15-30 days',
    requiredDocuments: ['Death Certificate', 'Income Certificate', 'Bank Details', 'Applicant ID'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'unemployment-allowance',
    slug: 'unemployment-allowance',
    name: 'Unemployment Allowance',
    description: 'Monthly allowance for unemployed youth',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 108,
    totalPayable: 707,
    nriGovtFee: 0,
    nriProfFee: 3594,
    nriGst: 647,
    nriTotalPayable: 4241,
    priceUSD: 51,
    priceGBP: 41,
    priceAED: 187,
    processingTime: '30-60 days',
    requiredDocuments: ['Educational Certificates', 'Income Certificate', 'Employment Office Registration', 'Bank Details'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'farmer-welfare',
    slug: 'farmer-welfare',
    name: 'Farmer Welfare Scheme',
    description: 'Various schemes for farmers',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 799,
    gst: 144,
    totalPayable: 943,
    nriGovtFee: 0,
    nriProfFee: 4794,
    nriGst: 863,
    nriTotalPayable: 5657,
    priceUSD: 68,
    priceGBP: 55,
    priceAED: 249,
    processingTime: '30-60 days',
    requiredDocuments: ['Land Records', 'Income Certificate', 'Bank Details', 'Aadhaar'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'free-laptop-scheme',
    slug: 'free-laptop-scheme',
    name: 'Free Laptop Scheme',
    description: 'Laptop distribution for students',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 399,
    gst: 72,
    totalPayable: 471,
    nriGovtFee: 0,
    nriProfFee: 2394,
    nriGst: 431,
    nriTotalPayable: 2825,
    priceUSD: 34,
    priceGBP: 27,
    priceAED: 126,
    processingTime: '60-90 days',
    requiredDocuments: ['Mark Sheets', 'College ID', 'Income Certificate', 'Bank Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'ration-card-subsidy',
    slug: 'ration-card-subsidy',
    name: 'Ration Card Subsidy',
    description: 'Food security card and subsidies',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 599,
    gst: 108,
    totalPayable: 707,
    nriGovtFee: 0,
    nriProfFee: 3594,
    nriGst: 647,
    nriTotalPayable: 4241,
    priceUSD: 51,
    priceGBP: 41,
    priceAED: 187,
    processingTime: '30-60 days',
    requiredDocuments: ['Family Details', 'Income Certificate', 'Address Proof', 'Aadhaar (All members)'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'health-insurance-scheme',
    slug: 'health-insurance-scheme',
    name: 'Health Insurance Scheme',
    description: 'Government health insurance enrollment',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 399,
    gst: 72,
    totalPayable: 471,
    nriGovtFee: 0,
    nriProfFee: 2394,
    nriGst: 431,
    nriTotalPayable: 2825,
    priceUSD: 34,
    priceGBP: 27,
    priceAED: 126,
    processingTime: '15-30 days',
    requiredDocuments: ['Family Details', 'Income Certificate', 'Aadhaar (All members)', 'Bank Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'skill-development-scheme',
    slug: 'skill-development-scheme',
    name: 'Skill Development Scheme',
    description: 'Free skill training programs',
    category: 'welfare',
    categoryGroup: 'Welfare Schemes',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 54,
    totalPayable: 353,
    nriGovtFee: 0,
    nriProfFee: 1794,
    nriGst: 323,
    nriTotalPayable: 2117,
    priceUSD: 26,
    priceGBP: 21,
    priceAED: 94,
    processingTime: '15-30 days',
    requiredDocuments: ['Educational Certificates', 'Aadhaar', 'Bank Details'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  // ========================================
  // BUSINESS & LICENSES (10 Services - Online Only)
  // ========================================
  {
    id: 'gst-registration',
    slug: 'gst-registration',
    name: 'GST Registration Services',
    description: 'GST registration, amendment, and cancellation - 100% online',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 3539,
    nriGovtFee: 0,
    nriProfFee: 17994,
    nriGst: 3239,
    nriTotalPayable: 21233,
    priceUSD: 256,
    priceGBP: 206,
    priceAED: 937,
    processingTime: '7-15 days',
    requiredDocuments: ['Business Address Proof', 'PAN Card', 'Bank Details', 'Owner ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: true,
    subServices: [
      { value: 'new', label: 'New GST Registration', description: 'Fresh GST registration for new business', additionalDocs: ['Business Registration', 'Bank Details'] },
      { value: 'amendment', label: 'GST Amendment', description: 'Modify existing GST registration details', additionalDocs: ['Existing GSTIN', 'Documents for Changes'] },
      { value: 'cancellation', label: 'GST Cancellation', description: 'Close/cancel GST registration', additionalDocs: ['Existing GSTIN', 'Final Returns'] }
    ]
  },

  {
    id: 'shops-establishment-license',
    slug: 'shops-establishment-license',
    name: 'Shops & Establishment License',
    description: 'Registration under Shops Act',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 200,
    professionalFee: 1499,
    gst: 270,
    totalPayable: 1969,
    nriGovtFee: 1200,
    nriProfFee: 8994,
    nriGst: 1619,
    nriTotalPayable: 11813,
    priceUSD: 142,
    priceGBP: 115,
    priceAED: 521,
    processingTime: '15-30 days',
    requiredDocuments: ['Shop Address Proof', 'Owner ID', 'Employee Details', 'Layout Plan'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'msme-udyam-registration',
    slug: 'msme-udyam-registration',
    name: 'MSME/Udyam Registration',
    description: 'Micro, Small & Medium Enterprise registration',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 0,
    professionalFee: 1999,
    gst: 360,
    totalPayable: 2359,
    nriGovtFee: 0,
    nriProfFee: 11994,
    nriGst: 2159,
    nriTotalPayable: 14153,
    priceUSD: 171,
    priceGBP: 138,
    priceAED: 626,
    processingTime: '7-15 days',
    requiredDocuments: ['Aadhaar', 'PAN', 'Business Details', 'Investment Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'import-export-code',
    slug: 'import-export-code',
    name: 'Import Export Code (IEC)',
    description: 'DGFT IEC for international trade',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 500,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 4039,
    nriGovtFee: 3000,
    nriProfFee: 17994,
    nriGst: 3239,
    nriTotalPayable: 24233,
    priceUSD: 292,
    priceGBP: 235,
    priceAED: 1069,
    processingTime: '7-15 days',
    requiredDocuments: ['PAN Card', 'Business Address Proof', 'Bank Certificate', 'Cancelled Cheque'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'professional-tax-registration',
    slug: 'professional-tax-registration',
    name: 'Professional Tax Registration',
    description: 'State professional tax enrollment',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 100,
    professionalFee: 999,
    gst: 180,
    totalPayable: 1279,
    nriGovtFee: 600,
    nriProfFee: 5994,
    nriGst: 1079,
    nriTotalPayable: 7673,
    priceUSD: 93,
    priceGBP: 74,
    priceAED: 340,
    processingTime: '7-15 days',
    requiredDocuments: ['PAN Card', 'Business Registration', 'Employee Details', 'Address Proof'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'contractor-license',
    slug: 'contractor-license',
    name: 'Contractor License',
    description: 'Building contractor registration',
    category: 'business',
    categoryGroup: 'Business & Licenses',
    statutoryFee: 1000,
    professionalFee: 4999,
    gst: 900,
    totalPayable: 6899,
    nriGovtFee: 6000,
    nriProfFee: 29994,
    nriGst: 5399,
    nriTotalPayable: 41393,
    priceUSD: 499,
    priceGBP: 401,
    priceAED: 1825,
    processingTime: '30-45 days',
    requiredDocuments: ['Technical Qualifications', 'Work Experience', 'PAN Card', 'Business Address'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  // ========================================
  // VEHICLE SERVICES (6 Services - Online Only)
  // ========================================
  {
    id: 'duplicate-rc',
    slug: 'duplicate-rc',
    name: 'Duplicate RC',
    description: 'Reissue lost or damaged RC',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 100,
    professionalFee: 699,
    gst: 126,
    totalPayable: 925,
    nriGovtFee: 600,
    nriProfFee: 4194,
    nriGst: 755,
    nriTotalPayable: 5549,
    priceUSD: 67,
    priceGBP: 54,
    priceAED: 244,
    processingTime: '7-15 days',
    requiredDocuments: ['FIR Copy (if lost)', 'Owner ID', 'Vehicle Photos', 'Insurance Copy'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'rc-address-change',
    slug: 'rc-address-change',
    name: 'RC Address Change',
    description: 'Update address in vehicle registration - 100% online',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 100,
    professionalFee: 799,
    gst: 144,
    totalPayable: 1043,
    nriGovtFee: 600,
    nriProfFee: 4794,
    nriGst: 863,
    nriTotalPayable: 6257,
    priceUSD: 75,
    priceGBP: 61,
    priceAED: 279,
    processingTime: '7-15 days',
    requiredDocuments: ['Original RC', 'New Address Proof', 'Owner ID', 'Form 28'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'hypothecation-removal',
    slug: 'hypothecation-removal',
    name: 'Hypothecation Removal',
    description: 'Remove loan lien from vehicle RC',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 100,
    professionalFee: 999,
    gst: 180,
    totalPayable: 1279,
    nriGovtFee: 600,
    nriProfFee: 5994,
    nriGst: 1079,
    nriTotalPayable: 7673,
    priceUSD: 93,
    priceGBP: 74,
    priceAED: 340,
    processingTime: '15-30 days',
    requiredDocuments: ['Original RC', 'NOC from Bank', 'Form 35', 'Owner ID'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'medium',
    hasSubServices: false
  },

  {
    id: 'road-tax-payment',
    slug: 'road-tax-payment',
    name: 'Road Tax Payment',
    description: 'Annual road tax payment',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 0,
    professionalFee: 299,
    gst: 54,
    totalPayable: 353,
    nriGovtFee: 0,
    nriProfFee: 1794,
    nriGst: 323,
    nriTotalPayable: 2117,
    priceUSD: 26,
    priceGBP: 21,
    priceAED: 94,
    processingTime: '3-7 days',
    requiredDocuments: ['RC Copy', 'Previous Tax Receipt', 'Vehicle Details'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'theft-intimation',
    slug: 'theft-intimation',
    name: 'Vehicle Theft Intimation',
    description: 'Report vehicle theft to RTO',
    category: 'vehicle',
    categoryGroup: 'Vehicle Services',
    statutoryFee: 0,
    professionalFee: 499,
    gst: 90,
    totalPayable: 589,
    nriGovtFee: 0,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3533,
    priceUSD: 43,
    priceGBP: 34,
    priceAED: 156,
    processingTime: '3-7 days',
    requiredDocuments: ['Vehicle Details', 'Owner ID', 'FIR Copy (if stolen)'],
    popular: false,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  // ========================================
  // LEGAL SERVICES (4 Services)
  // ========================================
  {
    id: 'affidavit-drafting',
    slug: 'affidavit-drafting',
    name: 'Affidavit Drafting',
    description: 'Legal affidavit preparation',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 50,
    professionalFee: 499,
    gst: 90,
    totalPayable: 639,
    nriGovtFee: 300,
    nriProfFee: 2994,
    nriGst: 539,
    nriTotalPayable: 3833,
    priceUSD: 46,
    priceGBP: 37,
    priceAED: 169,
    processingTime: '1-3 days',
    requiredDocuments: ['Purpose Details', 'Supporting Documents', 'ID Proof'],
    popular: true,
    isFullyOnline: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  {
    id: 'notary-services',
    slug: 'notary-services',
    name: 'Notary Services',
    description: 'Document notarization and attestation',
    category: 'legal',
    categoryGroup: 'Legal Services',
    statutoryFee: 100,
    professionalFee: 299,
    gst: 54,
    totalPayable: 453,
    nriGovtFee: 600,
    nriProfFee: 1794,
    nriGst: 323,
    nriTotalPayable: 2717,
    priceUSD: 33,
    priceGBP: 26,
    priceAED: 120,
    processingTime: '1-2 days',
    requiredDocuments: ['Original Documents', 'ID Proof', 'Photographs'],
    popular: true,
    operationalComplexity: 'low',
    hasSubServices: false
  },

  // ========================================
  // SAFETY & COMPLIANCE (1 Service)
  // ========================================
  {
    id: 'name-change-gazette',
    slug: 'name-change-gazette',
    name: 'Name Change Gazette',
    description: 'Legal name change through government gazette',
    category: 'identity',
    categoryGroup: 'Identity & Cards',
    statutoryFee: 500,
    professionalFee: 2999,
    gst: 540,
    totalPayable: 4039,
    nriGovtFee: 3000,
    nriProfFee: 17994,
    nriGst: 3239,
    nriTotalPayable: 24233,
    priceUSD: 292,
    priceGBP: 235,
    priceAED: 1069,
    processingTime: '45-60 days',
    requiredDocuments: ['Affidavit', 'Newspaper Advertisement', 'Aadhaar', 'Gazette Application'],
    popular: false,
    isFullyOnline: false,
    operationalComplexity: 'high',
    hasSubServices: false
  },
];

// ========================================
// PHASE 2 - SERVICES REQUIRING PHYSICAL PRESENCE
// These services are commented out and will be added in Phase 2
// ========================================

/*
// PASSPORT - All sub-services require PSK appointment
{
  id: 'passport-application-support',
  slug: 'passport-application-support',
  name: 'Passport Application Support',
  description: 'Complete assistance for new passport, renewal, or re-issue',
  category: 'identity',
  categoryGroup: 'Identity & Cards',
  statutoryFee: 1500,
  professionalFee: 799,
  gst: 144,
  totalPayable: 2443,
  processingTime: '30-45 days',
  requiredDocuments: ['Birth Certificate', 'Address Proof', 'Identity Proof', 'Passport Photos'],
  popular: true,
  requiresPhysicalPresence: true,
  isFullyOnline: false,
  operationalComplexity: 'medium',
  hasSubServices: true,
  subServices: [
    { value: 'new-normal', label: 'New Passport - 36 Pages', description: 'Standard 36-page passport', additionalDocs: ['Address Proof', 'Birth Certificate', 'Photos'] },
    { value: 'new-jumbo', label: 'New Passport - 60 Pages', description: '60-page passport for frequent travelers', additionalDocs: ['Address Proof', 'Birth Certificate', 'Photos', 'Justification Letter'] },
    { value: 'new-minor', label: 'Minor Passport', description: 'Passport for children under 18 years', additionalDocs: ['Birth Certificate', 'Parents Passport Copy', 'Photos', 'Annexure D'] },
    { value: 'renewal', label: 'Passport Renewal', description: 'Renew existing passport', additionalDocs: ['Old Passport', 'Address Proof'] },
    { value: 'reissue-address', label: 'Reissue - Address Change', description: 'Reissue for address change', additionalDocs: ['Proof of Address', 'Old Passport'] },
    { value: 'reissue-name', label: 'Reissue - Name Change', description: 'Reissue for name change', additionalDocs: ['Marriage Certificate or Gazette Notification', 'Old Passport'] },
    { value: 'reissue-spouse', label: 'Reissue - Spouse Addition', description: 'Add or remove spouse name', additionalDocs: ['Marriage Certificate', 'Spouse ID', 'Old Passport'] },
    { value: 'reissue-lost', label: 'Reissue - Lost/Damaged', description: 'Reissue lost or damaged passport', additionalDocs: ['FIR Copy', 'Affidavit of Loss'] }
  ]
},

// RATION CARD - All sub-services require TSO home inspection
{
  id: 'ration-card',
  slug: 'ration-card',
  name: 'Ration Card',
  description: 'New ration card, add/delete members, address change, card type conversion',
  category: 'identity',
  categoryGroup: 'Identity & Cards',
  statutoryFee: 0,
  professionalFee: 600,
  gst: 108,
  totalPayable: 708,
  processingTime: '45-60 days',
  requiredDocuments: ['Aadhaar Cards (All family members)', 'Address Proof', 'Income Proof', 'Passport Size Photos', 'Gas Connection Proof', 'Bank Passbook'],
  popular: true,
  requiresSiteInspection: true,
  isFullyOnline: false,
  operationalComplexity: 'medium',
  hasSubServices: true,
  subServices: [
    { value: 'new', label: 'New Ration Card', description: 'First-time ration card application', additionalDocs: ['Family Details', 'Income Certificate'] },
    { value: 'add_member', label: 'Add Family Member', description: 'Add new member to existing card', additionalDocs: ['Member Aadhaar', 'Relationship Proof', 'Existing Card'] },
    { value: 'delete_member', label: 'Delete Member', description: 'Remove member from card', additionalDocs: ['Reason Documentation', 'Existing Card'] },
    { value: 'address_change', label: 'Change Address (Same Taluk)', description: 'Update address within taluk', additionalDocs: ['New Address Proof', 'Existing Card'] },
    { value: 'transfer', label: 'Transfer Card (Different Taluk)', description: 'Transfer to different taluk/district', additionalDocs: ['New Address Proof', 'Surrender Certificate'] },
    { value: 'duplicate', label: 'Duplicate Card (Lost/Damaged)', description: 'Reissue ration card', additionalDocs: ['FIR (if lost)', 'Application'] },
    { value: 'surrender', label: 'Surrender Card', description: 'Voluntary surrender', additionalDocs: ['Reason Statement', 'Card to Surrender'] },
    { value: 'correction', label: 'Correction in Name/Details', description: 'Fix errors on card', additionalDocs: ['Proof of Correction', 'Existing Card'] },
    { value: 'conversion', label: 'Card Type Conversion (APL/BPL/AAY)', description: 'Change card category', additionalDocs: ['Income Certificate', 'Eligibility Proof'] }
  ]
},

// DISABILITY CERTIFICATE - Requires medical board examination
{
  id: 'disability-certificate',
  slug: 'disability-certificate',
  name: 'Disability Certificate',
  description: 'Differently abled certificate with medical board',
  category: 'identity',
  categoryGroup: 'Identity & Cards',
  statutoryFee: 0,
  professionalFee: 799,
  gst: 144,
  totalPayable: 943,
  processingTime: '30-60 days',
  requiredDocuments: ['Medical Reports', 'Aadhaar', 'Photographs', 'Medical Board Appointment'],
  popular: false,
  requiresPhysicalPresence: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

// MARRIAGE CERTIFICATE - Requires couple + witnesses at SRO
{
  id: 'marriage-certificate',
  slug: 'marriage-certificate',
  name: 'Marriage Certificate',
  description: 'Official marriage registration certificate',
  category: 'certificates',
  categoryGroup: 'Revenue Certificates',
  statutoryFee: 100,
  professionalFee: 799,
  gst: 144,
  totalPayable: 1043,
  processingTime: '15-30 days',
  requiredDocuments: ['Marriage Invitation', 'Photos', 'IDs of Couple', 'Witness Details'],
  popular: true,
  requiresPhysicalPresence: true,
  operationalComplexity: 'medium',
  hasSubServices: false
},

// INSPECTION-BASED BUSINESS LICENSES
{
  id: 'trade-license',
  slug: 'trade-license',
  name: 'Trade License',
  description: 'Municipal trade license for business',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 500,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2859,
  processingTime: '15-30 days',
  requiredDocuments: ['Shop/Office Address Proof', 'Owner ID', 'Business Details', 'Layout Plan'],
  popular: true,
  requiresSiteInspection: true,
  operationalComplexity: 'medium',
  hasSubServices: false
},

{
  id: 'food-license-fssai',
  slug: 'food-license-fssai',
  name: 'FSSAI Food License',
  description: 'Food Safety and Standards Authority license',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 2000,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 7899,
  processingTime: '30-60 days',
  requiredDocuments: ['Business Address Proof', 'Food Safety Plan', 'Layout Plan', 'Owner ID'],
  popular: true,
  requiresSiteInspection: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

{
  id: 'fire-noc',
  slug: 'fire-noc',
  name: 'Fire NOC',
  description: 'Fire safety NOC from fire department',
  category: 'business',
  categoryGroup: 'Business & Licenses',
  statutoryFee: 1000,
  professionalFee: 4999,
  gst: 900,
  totalPayable: 6899,
  processingTime: '30-45 days',
  requiredDocuments: ['Building Plan', 'Fire Safety Equipment Details', 'Layout Plan', 'Owner ID'],
  popular: true,
  requiresSiteInspection: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

// PROPERTY SERVICES REQUIRING INSPECTION
{
  id: 'building-permit',
  slug: 'building-permit',
  name: 'Building Construction Permit',
  description: 'Construction approval from local authority',
  category: 'property',
  categoryGroup: 'Property & Assets',
  statutoryFee: 5000,
  professionalFee: 14999,
  gst: 2700,
  totalPayable: 22699,
  processingTime: '60-90 days',
  requiredDocuments: ['Plot Details', 'Building Plan', 'Architect Certificate', 'Ownership Proof'],
  popular: false,
  requiresSiteInspection: true,
  isStatutoryFeeVariable: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

{
  id: 'occupancy-certificate',
  slug: 'occupancy-certificate',
  name: 'Occupancy Certificate',
  description: 'Post-construction occupancy approval',
  category: 'property',
  categoryGroup: 'Property & Assets',
  statutoryFee: 2000,
  professionalFee: 9999,
  gst: 1800,
  totalPayable: 13799,
  processingTime: '30-60 days',
  requiredDocuments: ['Building Permit', 'Completion Certificate', 'Site Photos', 'Compliance Report'],
  popular: false,
  requiresSiteInspection: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

{
  id: 'land-conversion',
  slug: 'land-conversion',
  name: 'Land Use Conversion',
  description: 'Agricultural to non-agricultural conversion',
  category: 'property',
  categoryGroup: 'Property & Assets',
  statutoryFee: 10000,
  professionalFee: 24999,
  gst: 4500,
  totalPayable: 39499,
  processingTime: '90-180 days',
  requiredDocuments: ['Patta Copy', 'Survey Map', 'FMB Sketch', 'Land Use Purpose'],
  popular: false,
  requiresSiteInspection: true,
  isStatutoryFeeVariable: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

// VEHICLE SERVICES REQUIRING PHYSICAL PRESENCE
{
  id: 'vehicle-registration',
  slug: 'vehicle-registration',
  name: 'New Vehicle Registration',
  description: 'First-time vehicle registration with RTO',
  category: 'vehicle',
  categoryGroup: 'Vehicle Services',
  statutoryFee: 300,
  professionalFee: 1299,
  gst: 234,
  totalPayable: 1833,
  processingTime: '7-15 days',
  requiredDocuments: ['Invoice', 'Insurance', 'Pollution Certificate', 'ID Proof', 'Address Proof'],
  popular: true,
  requiresPhysicalPresence: true,
  isStatutoryFeeVariable: true,
  operationalComplexity: 'medium',
  hasSubServices: false
},

{
  id: 'rc-transfer',
  slug: 'rc-transfer',
  name: 'RC Transfer (Ownership Change)',
  description: 'Transfer vehicle ownership',
  category: 'vehicle',
  categoryGroup: 'Vehicle Services',
  statutoryFee: 300,
  professionalFee: 1499,
  gst: 270,
  totalPayable: 2069,
  processingTime: '15-30 days',
  requiredDocuments: ['Original RC', 'Sale Agreement', 'Insurance', 'IDs of Both Parties', 'Form 29 & 30'],
  popular: true,
  requiresPhysicalPresence: true,
  operationalComplexity: 'medium',
  hasSubServices: false
},

{
  id: 'vehicle-fitness-certificate',
  slug: 'vehicle-fitness-certificate',
  name: 'Vehicle Fitness Certificate',
  description: 'Fitness certificate for commercial vehicles',
  category: 'vehicle',
  categoryGroup: 'Vehicle Services',
  statutoryFee: 200,
  professionalFee: 999,
  gst: 180,
  totalPayable: 1379,
  processingTime: '3-7 days',
  requiredDocuments: ['RC Copy', 'Insurance', 'Pollution Certificate', 'Vehicle Inspection'],
  popular: false,
  requiresPhysicalPresence: true,
  requiresSiteInspection: true,
  operationalComplexity: 'medium',
  hasSubServices: false
},

// LEGAL SERVICES REQUIRING PHYSICAL PRESENCE
{
  id: 'power-of-attorney',
  slug: 'power-of-attorney',
  name: 'Power of Attorney',
  description: 'POA preparation and registration',
  category: 'legal',
  categoryGroup: 'Legal Services',
  statutoryFee: 500,
  professionalFee: 1999,
  gst: 360,
  totalPayable: 2859,
  processingTime: '7-15 days',
  requiredDocuments: ['Grantor & Grantee IDs', 'Purpose Details', 'Witnesses'],
  popular: false,
  requiresPhysicalPresence: true,
  operationalComplexity: 'medium',
  hasSubServices: false
},

{
  id: 'succession-certificate',
  slug: 'succession-certificate',
  name: 'Succession Certificate',
  description: 'Court succession certificate for movable property',
  category: 'legal',
  categoryGroup: 'Legal Services',
  statutoryFee: 5000,
  professionalFee: 14999,
  gst: 2700,
  totalPayable: 22699,
  processingTime: '180-365 days',
  requiredDocuments: ['Death Certificate', 'Legal Heir Certificate', 'Property Details'],
  popular: false,
  requiresPhysicalPresence: true,
  isStatutoryFeeVariable: true,
  operationalComplexity: 'high',
  hasSubServices: false
},

{
  id: 'degree-certificate-verification',
  slug: 'degree-certificate-verification',
  name: 'Degree Certificate Verification',
  description: 'University degree certificate verification',
  category: 'education',
  categoryGroup: 'Education',
  statutoryFee: 100,
  professionalFee: 799,
  gst: 144,
  totalPayable: 1043,
  processingTime: '15-30 days',
  requiredDocuments: ['Original Degree', 'Mark Sheets', 'ID Proof'],
  popular: false,
  requiresPhysicalPresence: true,
  isFullyOnline: false,
  operationalComplexity: 'medium',
  hasSubServices: false
},
*/

// SERVICE CATEGORIES
export const serviceCategories = [
  { id: 'identity', name: 'Identity & Cards', icon: '≡ƒ¬¬', description: 'Aadhaar, PAN, Voter ID, Certificates' },
  { id: 'certificates', name: 'Revenue Certificates', icon: '≡ƒôä', description: 'Community, Income, Nativity certificates' },
  { id: 'property', name: 'Property & Assets', icon: '≡ƒÅá', description: 'Patta, Land records, Property services' },
  { id: 'vehicle', name: 'Vehicle Services', icon: '≡ƒÜù', description: 'RC services, Tax payments' },
  { id: 'business', name: 'Business & Licenses', icon: '≡ƒÆ╝', description: 'GST, MSME, Trade License' },
  { id: 'welfare', name: 'Welfare Schemes', icon: '≡ƒñ¥', description: 'Pensions, Scholarships, Social welfare' },
  { id: 'legal', name: 'Legal Services', icon: 'ΓÜû∩╕Å', description: 'Affidavits, Notary services' },
  { id: 'other', name: 'Other Services', icon: '≡ƒôï', description: 'Additional government services' }
];

// HELPER FUNCTIONS
export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(service => service.slug === slug);
}

export function getServicesByCategory(category: string): Service[] {
  return services.filter(service => service.category === category);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(services.map(service => service.category)));
}

export function getAllServices(): Service[] {
  return services;
}

export function getPopularServices(): Service[] {
  return services.filter(service => service.popular === true);
}

export function getOnlineServices(): Service[] {
  return services.filter(service => service.isFullyOnline === true);
}

export function searchServices(query: string): Service[] {
  const lowerQuery = query.toLowerCase();
  return services.filter(
    service =>
      service.name.toLowerCase().includes(lowerQuery) ||
      service.description.toLowerCase().includes(lowerQuery) ||
      service.category.toLowerCase().includes(lowerQuery)
  );
}

export function getCategoryInfo(categoryId: string) {
  return serviceCategories.find(cat => cat.id === categoryId);
}

export default services;
